[package]
name = "stu"
version = "0.6.5"
description = "TUI application for AWS S3 written in Rust using ratatui"
authors = ["Kyosuke Fujimoto <kyoro.f@gmail.com>"]
homepage = "https://github.com/lusingander/stu"
repository = "https://github.com/lusingander/stu"
readme = "README.md"
license = "MIT"
keywords = ["s3", "aws", "cli", "tui", "terminal"]
categories = ["command-line-utilities"]
edition = "2021"
rust-version = "1.81.0"

exclude = ["/.github", "/img", "/tool", "go.work*", "Makefile", "_config.yml"]

[dependencies]
ansi-to-tui = "7.0.0"
anyhow = "1.0.94"
arboard = "3.4.1"
aws-config = "1.5.11"
aws-sdk-s3 = "1.66.0"
aws-smithy-types = "1.2.10"
chrono = "0.4.39"
clap = { version = "4.5.23", features = ["derive"] }
dirs = "5.0.1"
humansize = "2.1.3"
image = "0.25.5"
infer = "0.16.0"
itsuki = "0.2.0"
laurier = "0.1.0"
once_cell = "1.20.2"
open = "5.3.1"
ratatui = { version = "0.29.0", features = ["unstable-widget-ref"] }
ratatui-image = "3.0.0"
serde = { version = "1.0.216", features = ["derive"] }
smart-default = "0.7.1"
syntect = { version = "5.2.0", default-features = false, features = [
    "default-fancy",
] }
textwrap = "0.16.1"
tokio = { version = "1.42.0", features = ["full"] }
toml = "0.8.19"
tracing = "0.1.41"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.19", features = ["chrono"] }
tui-input = "0.11.1"
umbra = "0.3.0"
roxmltree = "0.20.0"

[dev-dependencies]
rstest = "0.23.0"

[features]
imggen = [] # for test

[lints.clippy]
comparison_chain = "allow" # https://github.com/rust-lang/rust-clippy/issues/4725
